POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name": "Renato Spakauskas",
  "password": "2senha1",
  "email": "renato@home.org"
}

###
POST http://localhost:8000/api/register
Content-Type: application/json

{
  "name": "Camila Spakauskas",
  "password": "2Senha",
  "email": "kkps@home.com"
}

###
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "password": "2senha1",
  "email": "renato@home.org"
}

###
GET http://localhost:8000/api/user
Content-Type: application/json

###
POST http://localhost:8000/api/logout
Content-Type: application/json
